// Generated by installer/brand_tokens.py. Edit data/config/brand-tokens.json.
internal static class BrandTokens {
    public const string LightBackground = "#f5f7fc";
    public const string LightSurface = "#ffffff";
    public const string LightSoft = "#eef2fb";
    public const string LightText = "#1e2a52";
    public const string LightMuted = "#596981";
    public const string LightBorder = "#dbe3f2";
    public const string LightPrimary = "#3e5acf";
    public const string LightAccent = "#f39783";
    public const string DarkBackground = "#11192b";
    public const string DarkSurface = "#17223a";
    public const string DarkSoft = "#202d47";
    public const string DarkText = "#eef2fb";
    public const string DarkMuted = "#aabbda";
    public const string DarkBorder = "#314160";
    public const string DarkPrimary = "#3e5acf";
    public const string DarkAccent = "#f39783";
}
