"""Observed, serialized Auto Start input; caller retains the step until ready.

This controller owns only the pause-menu switch sequence, never tower inputs or round advancement.
"""
from copy import deepcopy
from math import isfinite


def autostart_ready(step, now, screen, observation, input_free, session_id,
                    press, click, persist=lambda: True, report=lambda message: None):
    """Return (confirmed_and_closed, issued_input) for an absolute switch intent.

    A saved phase is retry/cooldown metadata, not proof that the switch is still
    correct. session_id must be newly generated by the caller on each process
    start. No menu input is authorized by unknown labels or an ambiguous knob.
    """
    if not step or step.get('action') != 'set_autostart':
        return True, False
    if type(step.get('enabled')) is not bool:
        raise ValueError('Auto Start requires an absolute boolean state')
    if type(now) not in (int, float) or not isfinite(now):
        raise ValueError('Auto Start clock must be finite')
    if not isinstance(session_id, str) or not session_id:
        raise ValueError('Auto Start needs a fresh process session identifier')
    if not input_free or screen not in ('ingame', 'pause_menu'):
        return False, False
    pending = step.get('autostartPending')
    if pending is not None:
        if (not isinstance(pending, dict) or pending.get('phase') not in ('opening', 'toggling', 'closing')
                or type(pending.get('sentAt')) not in (int, float) or not isfinite(pending['sentAt'])
                or not isinstance(pending.get('session'), str)):
            raise ValueError('Invalid Auto Start checkpoint phase')
        # Clamp a backwards wall-clock jump, saving before any future input.
        if pending['sentAt'] > now:
            previous = deepcopy(pending)
            pending['sentAt'] = now
            if persist() is not True:
                step['autostartPending'] = previous
            return False, False
        if now - pending['sentAt'] < 1:
            return False, False
    if (screen == 'ingame' and pending and pending['phase'] == 'closing'
            and pending['session'] == session_id):
        return True, False

    def issue(phase, callback, *args):
        previous = deepcopy(step.get('autostartPending'))
        # Save the exact absolute intent before touching the game. On restart,
        # the new process observes the menu instead of replaying the old click.
        step['autostartPending'] = {'phase': phase, 'sentAt': now, 'session': session_id}
        if persist() is not True:
            if previous is None:
                step.pop('autostartPending', None)
            else:
                step['autostartPending'] = previous
            report('AUTOSTART checkpoint not saved; withholding input')
            return False, False
        callback(*args)
        report('AUTOSTART phase=' + phase + ' requested=' + str(step['enabled']))
        return False, True

    if screen == 'ingame':
        # This frame confirms that no pause menu is open. Do not repeat Esc
        # while a previous opening input could still be in transit.
        if pending and pending['phase'] == 'opening' and now - pending['sentAt'] < 3:
            return False, False
        return issue('opening', press, '{Esc}')
    if (not isinstance(observation, dict) or observation.get('pauseConfirmed') is not True
            or observation.get('status') != 'known' or type(observation.get('enabled')) is not bool):
        report('AUTOSTART switch unconfirmed; withholding menu input')
        return False, False
    if observation['enabled'] == step['enabled']:
        if pending and pending['phase'] == 'closing' and now - pending['sentAt'] < 3:
            return False, False
        return issue('closing', press, '{Esc}')
    position = observation.get('position')
    if (not isinstance(position, (tuple, list)) or len(position) != 2
            or any(type(value) not in (int, float) or not isfinite(value) or value < 0 for value in position)):
        report('AUTOSTART switch coordinates unconfirmed; withholding click')
        return False, False
    if pending and pending['phase'] == 'toggling' and now - pending['sentAt'] < 3:
        return False, False
    return issue('toggling', click, tuple(position))


def parse_autostart_command(line):
    """Parse an absolute route command, rejecting malformed reserved syntax."""
    if line in ('autostart on', 'autostart off'):
        return {'action': 'set_autostart', 'enabled': line == 'autostart on', 'cost': 0}
    if isinstance(line, str) and line.split(' ', 1)[0] == 'autostart':
        raise ValueError('Auto Start command must be exactly autostart on or autostart off')
    return None


def serialize_autostart_command(step):
    if not isinstance(step, dict) or step.get('action') != 'set_autostart' or type(step.get('enabled')) is not bool:
        raise ValueError('Auto Start command needs an absolute boolean intent')
    return 'autostart on' if step['enabled'] else 'autostart off'


def resume_autostart_intent(original, checkpoint):
    """Derive recheck intent from consumed source steps, never a cached setting.

    The caller must run this separately from remainingSteps before normal route
    actions. It is not a new recorded instruction and must not change indices.
    """
    if not isinstance(original, list) or not isinstance(checkpoint, dict):
        raise ValueError('Invalid Auto Start recovery data')
    offset = checkpoint.get('nextStep')
    if type(offset) is not int or not 0 <= offset <= len(original):
        raise ValueError('Invalid Auto Start recovery offset')
    intent = None
    for source in original[:offset]:
        if not isinstance(source, dict):
            raise ValueError('Invalid source route step')
        if source.get('action') == 'set_autostart':
            serialize_autostart_command(source)
            intent = {'action': 'set_autostart', 'enabled': source['enabled'], 'cost': 0}
    return intent


def restore_autostart_pending(source, saved):
    """Restore only a matching intent and well-formed retry phase."""
    serialize_autostart_command(source)
    if not isinstance(saved, dict) or saved.get('action') != source['action'] or saved.get('enabled') is not source['enabled']:
        raise ValueError('Auto Start checkpoint differs from the source intent')
    restored = deepcopy(source)
    pending = saved.get('autostartPending')
    if pending is not None:
        if (not isinstance(pending, dict) or pending.get('phase') not in ('opening', 'toggling', 'closing')
                or type(pending.get('sentAt')) not in (int, float) or not isfinite(pending['sentAt'])
                or not isinstance(pending.get('session'), str) or not pending['session']):
            raise ValueError('Invalid saved Auto Start phase')
        restored['autostartPending'] = {key: pending[key] for key in ('phase', 'sentAt', 'session')}
    return restored


def pending_autostart_step(config):
    recheck = config.get('resumeAutostartCheck')
    if recheck is not None:
        return recheck
    steps = config.get('steps', [])
    return steps[0] if steps and steps[0].get('action') == 'set_autostart' else None


def drive_autostart(config, now, screen, observation, input_free, session_id,
                    press, click, persist=lambda: True, report=lambda message: None):
    """Own this frame; dequeue only after observed closing and a saved commit.

    Resume rechecking stays outside the recorded queue, retaining its indices.
    Caller must defer competing inputs for every owned frame, including frames
    awaiting confirmation and checkpoint retries.
    """
    step = pending_autostart_step(config)
    if step is None:
        return False, False
    ready, issued = autostart_ready(step, now, screen, observation, input_free,
                                    session_id, press, click, persist, report)
    if not ready:
        return True, issued
    recheck = config.get('resumeAutostartCheck') is not None
    old_present = 'autostartEnabled' in config
    old_enabled = config.get('autostartEnabled')
    config['autostartEnabled'] = step['enabled']
    if recheck:
        config.pop('resumeAutostartCheck')
    else:
        config['steps'].pop(0)
    if persist() is not True:
        if recheck:
            config['resumeAutostartCheck'] = step
        else:
            config['steps'].insert(0, step)
        if old_present:
            config['autostartEnabled'] = old_enabled
        else:
            config.pop('autostartEnabled', None)
        report('AUTOSTART completion checkpoint not saved; retaining setting intent')
        return True, False
    report('AUTOSTART confirmed and closed enabled=' + str(step['enabled'])
           + (' resume-recheck' if recheck else ' route-step'))
    return True, False
