"""Generate dependency-free native/web constants from one checked token file."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render(config):
    colors = config.get('colors')
    required = {'background', 'surface', 'soft', 'text', 'muted', 'border', 'primary', 'accent'}
    if not isinstance(colors, dict) or set(colors) != {'light', 'dark'}:
        raise ValueError('Both installer themes are required')
    native = ['// Generated by installer/brand_tokens.py. Edit data/config/brand-tokens.json.',
              'internal static class BrandTokens {']
    web = ['/* Generated by installer/brand_tokens.py. Edit data/config/brand-tokens.json. */']
    for theme in ('light', 'dark'):
        palette = colors[theme]
        if not isinstance(palette, dict) or set(palette) != required:
            raise ValueError('Incomplete brand palette')
        web.append(':root {' if theme == 'light' else ':root[data-theme="dark"] {')
        for name, value in palette.items():
            if not isinstance(value, str) or not re.fullmatch(r'#[0-9a-f]{6}', value):
                raise ValueError('Invalid brand color')
            native.append(f'    public const string {theme.title()}{name.title()} = "{value}";')
            web.append(f'  --brand-{name}: {value};')
        web.append('}')
    native.append('}')
    return '\n'.join(native) + '\n', '\n'.join(web) + '\n'


def generate():
    native, web = render(json.loads((ROOT / 'data/config/brand-tokens.json').read_text(encoding='utf-8')))
    for file, text in ((ROOT / 'installer/native/BrandTokens.cs', native), (ROOT / 'assets/app/brand-tokens.css', web)):
        if not file.exists() or file.read_text(encoding='utf-8') != text:
            file.write_text(text, encoding='utf-8', newline='\n')


if __name__ == '__main__':
    generate()
